### ISSUE TITLE
Clean up the repository to remove malidrive dependencies

### ISSUE THREAD

**Issue by agalbachicar** [maliput/maliput_malidrive#160]
There are left some touch points or things the repository has as a former dependency of malidrive. Those should be changed to make things right:

- [x] Change installed headers. #162 
- [x] Remove `InertialToLaneMappingConfig` #163 https://github.com/ToyotaResearchInstitute/maliput_integration/pull/82
- [x] Unify `RoadNetworkBuilderBase` with `RoadNetworkBuilder` #164 
- [x] Unify `RoadGeometryBuilderBase` with `RoadGeometryBuilder` #166 

Follow up to https://github.com/ToyotaResearchInstitute/maliput_infrastructure/issues/224
