### ISSUE TITLE
[Meta] Fully support new rules API

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_malidrive#199]
Nowadays we are relying on old API for loading the rules however we partially populate new rules in order to exercise the API.
In order to fully support the new rules API:
 - [x] Support loading a RuleRegistry via yaml file. #193
 - [x] Support loading a RoadRulebook via yaml file using new rules format https://github.com/ToyotaResearchInstitute/maliput_malidrive/pull/198
 - [x] Verify PhaseRingBuilder continues to work correctly. 
      - [x] maliput issue: https://github.com/ToyotaResearchInstitute/maliput/issues/460
      - [x] Add tests.
 - [x] Adapt `maliput_integration`'s apps to support loading rule registry via yaml file.
